/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    profiles: Profile;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  displayName: string;
  slug: string;
  order: number;
  role: string;
  headline?: string | null;
  summary?: string | null;
  resumeLabel: string;
  /**
   * Use a unique resume link for this profile.
   */
  resumeHref: string;
  avatar?: (number | null) | Media;
  heroImage?: (number | null) | Media;
  accentColor: string;
  backgroundColor: string;
  textColor: string;
  themePreset:
    | 'elegantLuxury'
    | 'modernMinimal'
    | 'tangerine'
    | 'nature'
    | 'quantumRose'
    | 'sunsetHorizon'
    | 'mochaMousse';
  content?: {
    hero?: {
      title?: string | null;
      headline?: string | null;
      body?: string | null;
      image?: (number | null) | Media;
      ctaLabel?: string | null;
      ctaHref?: string | null;
    };
    about?: {
      title?: string | null;
      body?: string | null;
      educationLabel?: string | null;
      educationBody?: string | null;
      showTechStack?: boolean | null;
      techStackItems?:
        | (
            | 'typescript'
            | 'react'
            | 'next'
            | 'javascript'
            | 'tailwind'
            | 'graphql'
            | 'firebase'
            | 'nodejs'
            | 'mongodb'
            | 'postgresql'
            | 'prisma'
            | 'trpc'
            | 'vue'
            | 'svelte'
            | 'python'
            | 'docker'
            | 'figma'
            | 'framer'
            | 'redux'
            | 'zustand'
            | 'sass'
            | 'threejs'
            | 'gsap'
            | 'mern'
            | 'mean'
            | 'mevn'
            | 'pern'
            | 'pean'
            | 'pevn'
            | 'lamp'
            | 'lemp'
            | 'lapp'
            | 'wamp'
            | 'mamp'
            | 't3stack'
            | 'tallstack'
            | 'petalstack'
            | 'grandstack'
            | 'djangoreact'
            | 'djangovue'
            | 'djangohtmx'
            | 'flaskreact'
            | 'fastapinext'
            | 'laravelvue'
            | 'laravelreact'
            | 'railshotwire'
            | 'railsreact'
            | 'springbootangular'
            | 'springbootreact'
            | 'aspnetcoreblazor'
            | 'aspnetcorereact'
            | 'aspnetcoreangular'
            | 'sveltekitprisma'
            | 'nuxtnitro'
            | 'solidstartdrizzle'
            | 'remixprisma'
            | 'astrotailwind'
            | 'gatsbygraphql'
            | 'redwoodjs'
            | 'blitzjs'
            | 'meteorjs'
            | 'flutterfirebase'
            | 'reactnativeexpo'
            | 'ionicangular'
            | 'nativeios'
            | 'nativeandroid'
            | 'rustleptos'
            | 'rustaxyew'
            | 'goginreact'
            | 'goechohtmx'
            | 'clojureluminus'
            | 'serverlessstack'
            | 'firebasefullstack'
            | 'supabasefullstack'
            | 'appwritefullstack'
            | 'pocketbasefullstack'
            | 'strapiNext'
            | 'sanitygatsby'
            | 'shopifyhydrogenoxygen'
            | 'wordpressheadless'
            | 'odoo'
            | 'sapfiori'
            | 'mainframe'
          )[]
        | null;
      stats?:
        | {
            label: string;
            value: string;
            id?: string | null;
          }[]
        | null;
    };
    projects?: {
      title?: string | null;
      body?: string | null;
      items?:
        | {
            title: string;
            description: string;
            techStack?: string | null;
            image?: (number | null) | Media;
            liveUrl?: string | null;
            githubUrl?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    blog?: {
      title?: string | null;
      body?: string | null;
      posts?:
        | {
            title: string;
            description: string;
            image?: (number | null) | Media;
            publishAt?: string | null;
            link?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    contact?: {
      title?: string | null;
      body?: string | null;
      links?:
        | {
            label: string;
            href: string;
            id?: string | null;
          }[]
        | null;
    };
  };
  fontFamily: string;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  displayName?: T;
  slug?: T;
  order?: T;
  role?: T;
  headline?: T;
  summary?: T;
  resumeLabel?: T;
  resumeHref?: T;
  avatar?: T;
  heroImage?: T;
  accentColor?: T;
  backgroundColor?: T;
  textColor?: T;
  themePreset?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              title?: T;
              headline?: T;
              body?: T;
              image?: T;
              ctaLabel?: T;
              ctaHref?: T;
            };
        about?:
          | T
          | {
              title?: T;
              body?: T;
              educationLabel?: T;
              educationBody?: T;
              showTechStack?: T;
              techStackItems?: T;
              stats?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
            };
        projects?:
          | T
          | {
              title?: T;
              body?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    techStack?: T;
                    image?: T;
                    liveUrl?: T;
                    githubUrl?: T;
                    id?: T;
                  };
            };
        blog?:
          | T
          | {
              title?: T;
              body?: T;
              posts?:
                | T
                | {
                    title?: T;
                    description?: T;
                    image?: T;
                    publishAt?: T;
                    link?: T;
                    id?: T;
                  };
            };
        contact?:
          | T
          | {
              title?: T;
              body?: T;
              links?:
                | T
                | {
                    label?: T;
                    href?: T;
                    id?: T;
                  };
            };
      };
  fontFamily?: T;
  ctaLabel?: T;
  ctaHref?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  selectorTitle: string;
  selectorDescription: string;
  defaultAccentColor: string;
  defaultBackgroundColor: string;
  defaultTextColor: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  selectorTitle?: T;
  selectorDescription?: T;
  defaultAccentColor?: T;
  defaultBackgroundColor?: T;
  defaultTextColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}